service: splatnet2statink-lambda
frameworkVersion: '2'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  environment:
    CONFIG_TXT: ${ssm:/splatnet2statink/config~true}

functions:
  run:
    handler: handler.run
    timeout: 60
    events:
      # 0,2,4,... o'clock in UTC -> 1,3,5,... o'clock in JST
      - schedule: cron(5 0/2 * * ? *)
